Menampilkan list api movies versi 1
iammarwan104/Menampilkan-list-API-movies pull request #2
Opened 2023-10-20 09:11 UTC by iammarwan104

2023-10-23 06:40 UTC, muasdev requested changes

2023-10-23 06:40 UTC, muasdev commented on src/MenampilkanList.jsx
>              .then(response => {
buatkan kelas constant untuk variable" yang di sering atau berulang kali dipakai.

```suggestion
        fetch(`${BASE_URL}/?s=${inputan.value}&apikey=${API_KEY}`)
            .then(response => {
```

2023-10-23 06:40 UTC, muasdev commented on src/MenampilkanList.jsx
> +                console.log(datas);
hapus log ketika sudah tdk terpakai

2023-10-23 06:40 UTC, muasdev commented on src/MenampilkanList.jsx
> +    const [detileMovie, setDetileMovie] = useState(null)
bukan detile. tapi detail 🤣

2023-10-23 06:40 UTC, muasdev commented on src/MenampilkanList.jsx
> +        setDetileMovie(null)
bukan detile. tapi detail 🤣

2023-10-23 06:40 UTC, muasdev commented on src/MenampilkanList.jsx
> +    const [status, setStatus] = useState(false)
ini perlu di perjelas, status apa ?!

2023-10-23 06:40 UTC, muasdev commented on src/MenampilkanList.jsx
> +    function Shimmer() {
nama functionnya bisa diubah.
lebih jelas sepertinya kalau `showShimmer(`) atau `showLoading()`

2023-10-23 06:40 UTC, muasdev commented on src/MenampilkanList.jsx
>      function showModal(kopi) {
1. parameternya perlu diubah. kenapa kopi 🤣 
2. nama functionnya juga ubah. showModal tdk jelas. bikin nama fungsi yang sesuai tugas dari fungsi itu

2023-10-23 06:40 UTC, muasdev commented on src/MenampilkanList.jsx
> +    function kopi() {
ini masih terpakai? kalau sudah tidak dihapus saja.
kalau masih, ubah nama fungsinya

2023-10-23 06:40 UTC, muasdev commented on src/components/movieList/MovieList.jsx
> +export default function MovieList() {
sudah betul naming convention nya untuk penulisan nama function di react? 
coba kirim aturannya di sini nah.

sama lebih bagus sepertinya kalau GetMovieList()

2023-10-24 06:18 UTC, muasdev requested changes

2023-10-24 06:18 UTC, muasdev commented on src/MenampilkanList.jsx
> +
pisahkan base url dengan path atau parameternya

2023-10-24 06:18 UTC, muasdev commented on src/MenampilkanList.jsx
> +// https://dev.to/sathishskdev/part-1-naming-conventions-the-foundation-of-clean-code-51ng
bukan di comment di codenya. kirim saja ke grup.
terus ubah beberapa penamaan yang tidak sesuai.
misal, 
`export default function MovieList() {`

kalau dari referensi yang dikirimkan, untuk penamaan fungsi itu camelCase.
jadi harusnya : 
`export default function getMovieList() {`

2023-10-24 08:19 UTC, muasdev requested changes

2023-10-24 08:19 UTC, muasdev commented on src/MenampilkanList.jsx
> +        let endPoinGetMovies = `${BASE_URL}?s=${getNameMovie.value}&apikey=${API_KEY}`;
endpoint pakai `t`

2023-10-24 08:19 UTC, muasdev commented on src/MenampilkanList.jsx
> +        let endPointGetMovieDetail = `${BASE_URL}?i=${ID_MOVIE}&apikey=${API_KEY}`
endpoint kenapa ditulis endPoint? endpoint itu satu kata.
jadi lebih cocok `endpointGetMovieDetail`

2023-10-24 08:19 UTC, muasdev commented on src/MenampilkanList.jsx
> +export default function menampilkanList() {
sekalian pakai bahasa inggris untuk penamaannya. 
misal : showListMovie()

2023-10-24 08:19 UTC, muasdev commented on src/MenampilkanList.jsx
> +    function showModalDetail(id) {
showModalDetailMovie()

2023-10-24 11:46 UTC, muasdev requested changes

2023-10-24 11:46 UTC, muasdev commented on src/ShowList.jsx
> +export default function showList() {
gunakan nama fungsi yang lebih jelas, ini showList data apa?
bisa pakai showListMovies(), showListAllMovie() dll

2023-10-24 11:46 UTC, muasdev commented on src/ShowList.jsx
> +    //
tidak perlu di jelaskan kode per baris seperti ini. cukup rapikan penamaan variable, fungsi dll agar kode lebih mudah dibaca sama tim yang lain.

2023-10-24 12:22 UTC, iammarwan104 commented
memodifikasi nama file beserta nama functionnya

2023-10-24 12:22 UTC, iammarwan104 commented
memodifikasi nama file beserta nama functionnya

2023-10-24 12:23 UTC, iammarwan104 commented
memodifikasi nama file beserta nama functionnya

2023-10-24 12:40 UTC, muasdev approved these changes
LGTM 💯

2023-10-24 13:07 UTC, yusril86 approved these changes

2023-10-25 07:17 UTC, merged